name: Build and Release

on:
  push:
    tags:
      - v*

  workflow_dispatch:

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 16.3.0

      - name: Write tag version into manifest.json
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npx json -I -f manifest.json -e "this.version='$(echo ${GITHUB_REF/refs\/tags\//} | sed 's/v//')'"
          npx json -I -f package.json -e "this.version='$(echo ${GITHUB_REF/refs\/tags\//} | sed 's/v//')'"

      - name: NPM install
        run: npm install

      - name: Build
        run: npm run-script build

      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: YoutubeClipPlaylist.zip
          # https://github.com/vimtor/action-zip/issues/8#issuecomment-917654348
          recursive: true

      - name: Build DEBUG
        run: npm run-script build:dev

      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: YoutubeClipPlaylist_DEBUG.zip
          # https://github.com/vimtor/action-zip/issues/8#issuecomment-917654348
          recursive: true

      - name: Attest Build Provenance for Release Build
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: YoutubeClipPlaylist.zip

      - name: Attest Build Provenance for Debug Build
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: YoutubeClipPlaylist_DEBUG.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: artifact
          path: |
            YoutubeClipPlaylist.zip
            YoutubeClipPlaylist_DEBUG.zip
            NOTICE
          retention-days: 10

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: artifact

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: NOTICE
          files: |
            YoutubeClipPlaylist.zip
            YoutubeClipPlaylist_DEBUG.zip
